### PR TITLE
Remove prov fork dependency

### PR DESCRIPTION
**Pull request by B-Stefan**
I removed the fork and fixed a bug within the prov_apil.py

### CODE REVIEW

**Comment by Drake81** [comment]
We should fix the Makefile and the travis.yml before merging this pull request

**Comment by B-Stefan** [comment]
Im  searching for the error currently ;)

**Comment by Drake81** [comment]
Change travis.yml to this version: https://github.com/DLR-SC/prov-db-connector/commit/3dd82e8f8dc1c14b36c9ac15c5c2eb006d55a4c2#diff-354f30a63fb0907d4ad57269548329e3

In Makefile change line 16/17 and 22/23

**Comment by Drake81** [comment]
In travis.yml: lines 17-19 could be replaced by line 16

**Pull request merged**
